//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBindingDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfBindingDemo.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние.
        /// </summary>
        internal static string Default_CheckBox_Content {
            get {
                return ResourceManager.GetString("Default_CheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CheckBox:.
        /// </summary>
        internal static string Default_CheckBox_Label {
            get {
                return ResourceManager.GetString("Default_CheckBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измени это значение.
        /// </summary>
        internal static string Default_DemoValue_Initial {
            get {
                return ResourceManager.GetString("Default_DemoValue_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каждый элемент WPF имеет режим привязки по умолчанию. Если не указать Mode явно, используется этот режим..
        /// </summary>
        internal static string Default_Description {
            get {
                return ResourceManager.GetString("Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попробуйте изменить значение в верхнем TextBox и посмотрите, как ведут себя разные элементы.
        /// </summary>
        internal static string Default_Group1_Hint {
            get {
                return ResourceManager.GetString("Default_Group1_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Демонстрация: одно свойство, разные элементы.
        /// </summary>
        internal static string Default_Group1_Title {
            get {
                return ResourceManager.GetString("Default_Group1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попробуйте изменить текст в каждом TextBox. Первый обновит значение, второй - нет..
        /// </summary>
        internal static string Default_Group2_Hint {
            get {
                return ResourceManager.GetString("Default_Group2_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Два одинаковых TextBox с разными привязками:.
        /// </summary>
        internal static string Default_Group2_Intro {
            get {
                return ResourceManager.GetString("Default_Group2_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сравнение: Default Mode vs Явное указание Mode.
        /// </summary>
        internal static string Default_Group2_Title {
            get {
                return ResourceManager.GetString("Default_Group2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Элементы OneWay (по умолчанию):.
        /// </summary>
        internal static string Default_OneWayElements_Title {
            get {
                return ResourceManager.GetString("Default_OneWayElements_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProgressBar:.
        /// </summary>
        internal static string Default_ProgressBar_Label {
            get {
                return ResourceManager.GetString("Default_ProgressBar_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение: {0}.
        /// </summary>
        internal static string Default_ProgressBar_ValueFormat {
            get {
                return ResourceManager.GetString("Default_ProgressBar_ValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slider:.
        /// </summary>
        internal static string Default_Slider_Label {
            get {
                return ResourceManager.GetString("Default_Slider_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходное значение (можно менять):.
        /// </summary>
        internal static string Default_Source_Label {
            get {
                return ResourceManager.GetString("Default_Source_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тестовый текст.
        /// </summary>
        internal static string Default_TestProperty_Initial {
            get {
                return ResourceManager.GetString("Default_TestProperty_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextBlock (только чтение):.
        /// </summary>
        internal static string Default_TextBlock_Label {
            get {
                return ResourceManager.GetString("Default_TextBlock_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextBox (редактирование):.
        /// </summary>
        internal static string Default_TextBox_Label {
            get {
                return ResourceManager.GetString("Default_TextBox_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Используется TwoWay (по умолчанию для TextBox).
        /// </summary>
        internal static string Default_TextBox_NoMode_Hint {
            get {
                return ResourceManager.GetString("Default_TextBox_NoMode_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextBox без указания Mode:.
        /// </summary>
        internal static string Default_TextBox_NoMode_Title {
            get {
                return ResourceManager.GetString("Default_TextBox_NoMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Явно указан OneWay, игнорирует default.
        /// </summary>
        internal static string Default_TextBox_OneWay_Hint {
            get {
                return ResourceManager.GetString("Default_TextBox_OneWay_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextBox с Mode=OneWay:.
        /// </summary>
        internal static string Default_TextBox_OneWay_Title {
            get {
                return ResourceManager.GetString("Default_TextBox_OneWay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка по-умолчанию.
        /// </summary>
        internal static string Default_Title {
            get {
                return ResourceManager.GetString("Default_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Элементы TwoWay (по умолчанию):.
        /// </summary>
        internal static string Default_TwoWayElements_Title {
            get {
                return ResourceManager.GetString("Default_TwoWayElements_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение:.
        /// </summary>
        internal static string Default_Value_Label {
            get {
                return ResourceManager.GetString("Default_Value_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык:.
        /// </summary>
        internal static string Language_Label {
            get {
                return ResourceManager.GetString("Language_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WPF Binding Demo.
        /// </summary>
        internal static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить свойство вручную.
        /// </summary>
        internal static string OneTime_Button_Update {
            get {
                return ResourceManager.GetString("OneTime_Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка OneTime устанавливается только один раз при инициализации и не обновляется при изменении источника..
        /// </summary>
        internal static string OneTime_Description {
            get {
                return ResourceManager.GetString("OneTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Прямая привязка к элементу.
        /// </summary>
        internal static string OneTime_Group1 {
            get {
                return ResourceManager.GetString("OneTime_Group1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2. Привязка через ViewModel.
        /// </summary>
        internal static string OneTime_Group2 {
            get {
                return ResourceManager.GetString("OneTime_Group2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попробуйте изменить текст в TextBox выше - этот TextBlock не обновится.
        /// </summary>
        internal static string OneTime_Hint_ChangeText {
            get {
                return ResourceManager.GetString("OneTime_Hint_ChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneTime привязка НЕ обновится даже при изменении свойства в ViewModel.
        /// </summary>
        internal static string OneTime_Hint_NoUpdate {
            get {
                return ResourceManager.GetString("OneTime_Hint_NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальное значение из ViewModel.
        /// </summary>
        internal static string OneTime_InitialValueFromViewModel {
            get {
                return ResourceManager.GetString("OneTime_InitialValueFromViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneTime привязка к TextBox выше:.
        /// </summary>
        internal static string OneTime_Label_OneTimeBinding {
            get {
                return ResourceManager.GetString("OneTime_Label_OneTimeBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneTime привязка к тому же свойству:.
        /// </summary>
        internal static string OneTime_Label_OneTimeToVM {
            get {
                return ResourceManager.GetString("OneTime_Label_OneTimeToVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходное значение:.
        /// </summary>
        internal static string OneTime_Label_OriginalValue {
            get {
                return ResourceManager.GetString("OneTime_Label_OriginalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение из ViewModel:.
        /// </summary>
        internal static string OneTime_Label_ValueFromVM {
            get {
                return ResourceManager.GetString("OneTime_Label_ValueFromVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новое значение: {0}.
        /// </summary>
        internal static string OneTime_NewValue_Format {
            get {
                return ResourceManager.GetString("OneTime_NewValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одноразовая привязка.
        /// </summary>
        internal static string OneTime_Title {
            get {
                return ResourceManager.GetString("OneTime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тестовый текст.
        /// </summary>
        internal static string OneWay_ComparisonSource_DefaultText {
            get {
                return ResourceManager.GetString("OneWay_ComparisonSource_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вычисляемые свойства (OneWay, только для чтения):.
        /// </summary>
        internal static string OneWay_Computed_Label {
            get {
                return ResourceManager.GetString("OneWay_Computed_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Односторонняя привязка обновляет цель при изменении источника, но изменения цели НЕ влияют на источник..
        /// </summary>
        internal static string OneWay_Description {
            get {
                return ResourceManager.GetString("OneWay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разность:.
        /// </summary>
        internal static string OneWay_Difference_Label {
            get {
                return ResourceManager.GetString("OneWay_Difference_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение: .
        /// </summary>
        internal static string OneWay_Format_Prefix {
            get {
                return ResourceManager.GetString("OneWay_Format_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение: {0}.
        /// </summary>
        internal static string OneWay_Format_Value {
            get {
                return ResourceManager.GetString("OneWay_Format_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Прямая OneWay привязка между элементами.
        /// </summary>
        internal static string OneWay_Group1 {
            get {
                return ResourceManager.GetString("OneWay_Group1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение слайдера обновляет ProgressBar и TextBlock, но обратно - нет.
        /// </summary>
        internal static string OneWay_Group1_Hint {
            get {
                return ResourceManager.GetString("OneWay_Group1_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slider → ProgressBar (OneWay):.
        /// </summary>
        internal static string OneWay_Group1_SliderText {
            get {
                return ResourceManager.GetString("OneWay_Group1_SliderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение:.
        /// </summary>
        internal static string OneWay_Group1_ValueLabel {
            get {
                return ResourceManager.GetString("OneWay_Group1_ValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2. OneWay привязка через ViewModel.
        /// </summary>
        internal static string OneWay_Group2 {
            get {
                return ResourceManager.GetString("OneWay_Group2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все элементы обновляются при изменении TextBox, но не могут изменить его.
        /// </summary>
        internal static string OneWay_Group2_Hint {
            get {
                return ResourceManager.GetString("OneWay_Group2_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3. OneWay vs Default Binding Mode.
        /// </summary>
        internal static string OneWay_Group3 {
            get {
                return ResourceManager.GetString("OneWay_Group3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим по умолчанию:.
        /// </summary>
        internal static string OneWay_Group3_DefaultMode_Label {
            get {
                return ResourceManager.GetString("OneWay_Group3_DefaultMode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для TextBlock Mode=OneWay установлен по умолчанию:.
        /// </summary>
        internal static string OneWay_Group3_DefaultMode_Title {
            get {
                return ResourceManager.GetString("OneWay_Group3_DefaultMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Явно указан OneWay:.
        /// </summary>
        internal static string OneWay_Group3_ExplicitOneWay {
            get {
                return ResourceManager.GetString("OneWay_Group3_ExplicitOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оба работают одинаково, так как OneWay - default для TextBlock.
        /// </summary>
        internal static string OneWay_Group3_SameBehavior {
            get {
                return ResourceManager.GetString("OneWay_Group3_SameBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4. OneWay к вычисляемому свойству.
        /// </summary>
        internal static string OneWay_Group4 {
            get {
                return ResourceManager.GetString("OneWay_Group4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Два числа (TwoWay привязка):.
        /// </summary>
        internal static string OneWay_Group4_TwoNumbers {
            get {
                return ResourceManager.GetString("OneWay_Group4_TwoNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина:.
        /// </summary>
        internal static string OneWay_Length_Label {
            get {
                return ResourceManager.GetString("OneWay_Length_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на символов.
        /// </summary>
        internal static string OneWay_Length_Suffix {
            get {
                return ResourceManager.GetString("OneWay_Length_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число A:.
        /// </summary>
        internal static string OneWay_NumberA_Label {
            get {
                return ResourceManager.GetString("OneWay_NumberA_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число B:.
        /// </summary>
        internal static string OneWay_NumberB_Label {
            get {
                return ResourceManager.GetString("OneWay_NumberB_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneWay привязки к одному свойству:.
        /// </summary>
        internal static string OneWay_OneWayBindings_Label {
            get {
                return ResourceManager.GetString("OneWay_OneWayBindings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произведение:.
        /// </summary>
        internal static string OneWay_Product_Label {
            get {
                return ResourceManager.GetString("OneWay_Product_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходное значение.
        /// </summary>
        internal static string OneWay_Source_DefaultValue {
            get {
                return ResourceManager.GetString("OneWay_Source_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Источник данных (можно менять):.
        /// </summary>
        internal static string OneWay_Source_Label {
            get {
                return ResourceManager.GetString("OneWay_Source_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма:.
        /// </summary>
        internal static string OneWay_Sum_Label {
            get {
                return ResourceManager.GetString("OneWay_Sum_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Односторонняя привязка.
        /// </summary>
        internal static string OneWay_Title {
            get {
                return ResourceManager.GetString("OneWay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальное значение.
        /// </summary>
        internal static string SourceTextBox_DefaultText {
            get {
                return ResourceManager.GetString("SourceTextBox_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка по-умолчанию.
        /// </summary>
        internal static string Tab_DefaultBinding {
            get {
                return ResourceManager.GetString("Tab_DefaultBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одноразовая привязка.
        /// </summary>
        internal static string Tab_OneTimeBinding {
            get {
                return ResourceManager.GetString("Tab_OneTimeBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Односторонняя привязка.
        /// </summary>
        internal static string Tab_OneWayBinding {
            get {
                return ResourceManager.GetString("Tab_OneWayBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Триггеры.
        /// </summary>
        internal static string Tab_Triggers {
            get {
                return ResourceManager.GetString("Tab_Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двусторонняя привязка.
        /// </summary>
        internal static string Tab_TwoWayBinding {
            get {
                return ResourceManager.GetString("Tab_TwoWayBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Запуск: изменение данных.
        /// </summary>
        internal static string Triggers_Comparison_DataTrigger_Line1 {
            get {
                return ResourceManager.GetString("Triggers_Comparison_DataTrigger_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Пример: значение TextBox.
        /// </summary>
        internal static string Triggers_Comparison_DataTrigger_Line2 {
            get {
                return ResourceManager.GetString("Triggers_Comparison_DataTrigger_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Гибкий, зависит от данных.
        /// </summary>
        internal static string Triggers_Comparison_DataTrigger_Line3 {
            get {
                return ResourceManager.GetString("Triggers_Comparison_DataTrigger_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DataTrigger.
        /// </summary>
        internal static string Triggers_Comparison_DataTrigger_Title {
            get {
                return ResourceManager.GetString("Triggers_Comparison_DataTrigger_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Запуск: событие.
        /// </summary>
        internal static string Triggers_Comparison_EventTrigger_Line1 {
            get {
                return ResourceManager.GetString("Triggers_Comparison_EventTrigger_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Пример: Click.
        /// </summary>
        internal static string Triggers_Comparison_EventTrigger_Line2 {
            get {
                return ResourceManager.GetString("Triggers_Comparison_EventTrigger_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Для анимаций.
        /// </summary>
        internal static string Triggers_Comparison_EventTrigger_Line3 {
            get {
                return ResourceManager.GetString("Triggers_Comparison_EventTrigger_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EventTrigger.
        /// </summary>
        internal static string Triggers_Comparison_EventTrigger_Title {
            get {
                return ResourceManager.GetString("Triggers_Comparison_EventTrigger_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Запуск: несколько условий.
        /// </summary>
        internal static string Triggers_Comparison_MultiDataTrigger_Line1 {
            get {
                return ResourceManager.GetString("Triggers_Comparison_MultiDataTrigger_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Пример: все CheckBox=true.
        /// </summary>
        internal static string Triggers_Comparison_MultiDataTrigger_Line2 {
            get {
                return ResourceManager.GetString("Triggers_Comparison_MultiDataTrigger_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Сложные условия.
        /// </summary>
        internal static string Triggers_Comparison_MultiDataTrigger_Line3 {
            get {
                return ResourceManager.GetString("Triggers_Comparison_MultiDataTrigger_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MultiDataTrigger.
        /// </summary>
        internal static string Triggers_Comparison_MultiDataTrigger_Title {
            get {
                return ResourceManager.GetString("Triggers_Comparison_MultiDataTrigger_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Запуск: изменение свойства.
        /// </summary>
        internal static string Triggers_Comparison_PropertyTrigger_Line1 {
            get {
                return ResourceManager.GetString("Triggers_Comparison_PropertyTrigger_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Пример: IsMouseOver.
        /// </summary>
        internal static string Triggers_Comparison_PropertyTrigger_Line2 {
            get {
                return ResourceManager.GetString("Triggers_Comparison_PropertyTrigger_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Прост в использовании.
        /// </summary>
        internal static string Triggers_Comparison_PropertyTrigger_Line3 {
            get {
                return ResourceManager.GetString("Triggers_Comparison_PropertyTrigger_Line3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PropertyTrigger.
        /// </summary>
        internal static string Triggers_Comparison_PropertyTrigger_Title {
            get {
                return ResourceManager.GetString("Triggers_Comparison_PropertyTrigger_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сравнение триггеров:.
        /// </summary>
        internal static string Triggers_Comparison_Title {
            get {
                return ResourceManager.GetString("Triggers_Comparison_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Триггеры позволяют автоматически изменять свойства элементов при определенных условиях..
        /// </summary>
        internal static string Triggers_Description {
            get {
                return ResourceManager.GetString("Triggers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наведи на меня мышь.
        /// </summary>
        internal static string Triggers_Group1_Button {
            get {
                return ResourceManager.GetString("Triggers_Group1_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срабатывает при изменении свойства элемента (IsMouseOver, IsPressed).
        /// </summary>
        internal static string Triggers_Group1_Hint {
            get {
                return ResourceManager.GetString("Triggers_Group1_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кнопка меняет цвет при наведении мыши (IsMouseOver) и при нажатии (IsPressed):.
        /// </summary>
        internal static string Triggers_Group1_Intro {
            get {
                return ResourceManager.GetString("Triggers_Group1_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Property Trigger (запускается при изменении свойства).
        /// </summary>
        internal static string Triggers_Group1_Title {
            get {
                return ResourceManager.GetString("Triggers_Group1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка состояния.
        /// </summary>
        internal static string Triggers_Group2_BorderText {
            get {
                return ResourceManager.GetString("Triggers_Group2_BorderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срабатывает при изменении данных, а не свойств элемента.
        /// </summary>
        internal static string Triggers_Group2_Hint {
            get {
                return ResourceManager.GetString("Triggers_Group2_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет рамки зависит от значения в TextBox:.
        /// </summary>
        internal static string Triggers_Group2_Intro {
            get {
                return ResourceManager.GetString("Triggers_Group2_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введи &apos;active&apos; или &apos;error&apos;.
        /// </summary>
        internal static string Triggers_Group2_TextBox_Placeholder {
            get {
                return ResourceManager.GetString("Triggers_Group2_TextBox_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2. Data Trigger (запускается при изменении данных).
        /// </summary>
        internal static string Triggers_Group2_Title {
            get {
                return ResourceManager.GetString("Triggers_Group2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить.
        /// </summary>
        internal static string Triggers_Group3_Button {
            get {
                return ResourceManager.GetString("Triggers_Group3_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обязательное условие 1.
        /// </summary>
        internal static string Triggers_Group3_Check1 {
            get {
                return ResourceManager.GetString("Triggers_Group3_Check1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обязательное условие 2.
        /// </summary>
        internal static string Triggers_Group3_Check2 {
            get {
                return ResourceManager.GetString("Triggers_Group3_Check2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срабатывает только при выполнении ВСЕХ условий.
        /// </summary>
        internal static string Triggers_Group3_Hint {
            get {
                return ResourceManager.GetString("Triggers_Group3_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кнопка активируется только когда оба CheckBox отмечены:.
        /// </summary>
        internal static string Triggers_Group3_Intro {
            get {
                return ResourceManager.GetString("Triggers_Group3_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3. MultiData Trigger (несколько условий).
        /// </summary>
        internal static string Triggers_Group3_Title {
            get {
                return ResourceManager.GetString("Triggers_Group3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажми для анимации.
        /// </summary>
        internal static string Triggers_Group4_Button {
            get {
                return ResourceManager.GetString("Triggers_Group4_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срабатывает при событии (Click, MouseEnter и т.д.), обычно для анимаций.
        /// </summary>
        internal static string Triggers_Group4_Hint {
            get {
                return ResourceManager.GetString("Triggers_Group4_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анимация при нажатии на кнопку:.
        /// </summary>
        internal static string Triggers_Group4_Intro {
            get {
                return ResourceManager.GetString("Triggers_Group4_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4. Event Trigger (запускается при событии).
        /// </summary>
        internal static string Triggers_Group4_Title {
            get {
                return ResourceManager.GetString("Triggers_Group4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Триггеры.
        /// </summary>
        internal static string Triggers_Title {
            get {
                return ResourceManager.GetString("Triggers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        internal static string TwoWay_Active_No {
            get {
                return ResourceManager.GetString("TwoWay_Active_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        internal static string TwoWay_Active_Yes {
            get {
                return ResourceManager.GetString("TwoWay_Active_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возраст: .
        /// </summary>
        internal static string TwoWay_Age_Prefix {
            get {
                return ResourceManager.GetString("TwoWay_Age_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя: {0}, Возраст: {1}, Активен: {2}.
        /// </summary>
        internal static string TwoWay_CurrentValues_Format {
            get {
                return ResourceManager.GetString("TwoWay_CurrentValues_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двухсторонняя привязка обновляет и источник, и цель при изменениях в любую сторону..
        /// </summary>
        internal static string TwoWay_Description {
            get {
                return ResourceManager.GetString("TwoWay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Прямая TwoWay привязка между элементами.
        /// </summary>
        internal static string TwoWay_Group1 {
            get {
                return ResourceManager.GetString("TwoWay_Group1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение ползунка обновляет TextBox и наоборот.
        /// </summary>
        internal static string TwoWay_Group1_Hint {
            get {
                return ResourceManager.GetString("TwoWay_Group1_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Slider и TextBox связаны TwoWay привязкой:.
        /// </summary>
        internal static string TwoWay_Group1_SliderText {
            get {
                return ResourceManager.GetString("TwoWay_Group1_SliderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2. TwoWay привязка через ViewModel.
        /// </summary>
        internal static string TwoWay_Group2 {
            get {
                return ResourceManager.GetString("TwoWay_Group2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3. Разница UpdateSourceTrigger.
        /// </summary>
        internal static string TwoWay_Group3 {
            get {
                return ResourceManager.GetString("TwoWay_Group3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущие значения в ViewModel:.
        /// </summary>
        internal static string TwoWay_Summary_Title {
            get {
                return ResourceManager.GetString("TwoWay_Summary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двусторонняя привязка.
        /// </summary>
        internal static string TwoWay_Title {
            get {
                return ResourceManager.GetString("TwoWay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить источник.
        /// </summary>
        internal static string TwoWay_UpdateSourceTrigger_Button {
            get {
                return ResourceManager.GetString("TwoWay_UpdateSourceTrigger_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PropertyChanged (обновление при каждом изменении):.
        /// </summary>
        internal static string TwoWay_UpdateSourceTrigger_Title1 {
            get {
                return ResourceManager.GetString("TwoWay_UpdateSourceTrigger_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LostFocus (обновление при потере фокуса):.
        /// </summary>
        internal static string TwoWay_UpdateSourceTrigger_Title2 {
            get {
                return ResourceManager.GetString("TwoWay_UpdateSourceTrigger_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Explicit (обновление только при вызове UpdateSource):.
        /// </summary>
        internal static string TwoWay_UpdateSourceTrigger_Title3 {
            get {
                return ResourceManager.GetString("TwoWay_UpdateSourceTrigger_Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иван Иванов.
        /// </summary>
        internal static string TwoWay_UserName_Default {
            get {
                return ResourceManager.GetString("TwoWay_UserName_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус активности: .
        /// </summary>
        internal static string TwoWay_VM_ActiveStatusLabel {
            get {
                return ResourceManager.GetString("TwoWay_VM_ActiveStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возраст:.
        /// </summary>
        internal static string TwoWay_VM_AgeLabel {
            get {
                return ResourceManager.GetString("TwoWay_VM_AgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все элементы связаны с одним свойством ViewModel:.
        /// </summary>
        internal static string TwoWay_VM_Intro {
            get {
                return ResourceManager.GetString("TwoWay_VM_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь активен.
        /// </summary>
        internal static string TwoWay_VM_IsActiveContent {
            get {
                return ResourceManager.GetString("TwoWay_VM_IsActiveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активен:.
        /// </summary>
        internal static string TwoWay_VM_IsActiveLabel {
            get {
                return ResourceManager.GetString("TwoWay_VM_IsActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя:.
        /// </summary>
        internal static string TwoWay_VM_UserNameLabel {
            get {
                return ResourceManager.GetString("TwoWay_VM_UserNameLabel", resourceCulture);
            }
        }
    }
}
