//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBindingDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfBindingDemo.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык:.
        /// </summary>
        internal static string Language_Label {
            get {
                return ResourceManager.GetString("Language_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WPF Binding Demo.
        /// </summary>
        internal static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить свойство вручную.
        /// </summary>
        internal static string OneTime_Button_Update {
            get {
                return ResourceManager.GetString("OneTime_Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка OneTime устанавливается только один раз при инициализации и не обновляется при изменении источника..
        /// </summary>
        internal static string OneTime_Description {
            get {
                return ResourceManager.GetString("OneTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Прямая привязка к элементу.
        /// </summary>
        internal static string OneTime_Group1 {
            get {
                return ResourceManager.GetString("OneTime_Group1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2. Привязка через ViewModel.
        /// </summary>
        internal static string OneTime_Group2 {
            get {
                return ResourceManager.GetString("OneTime_Group2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попробуйте изменить текст в TextBox выше - этот TextBlock не обновится.
        /// </summary>
        internal static string OneTime_Hint_ChangeText {
            get {
                return ResourceManager.GetString("OneTime_Hint_ChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneTime привязка НЕ обновится даже при изменении свойства в ViewModel.
        /// </summary>
        internal static string OneTime_Hint_NoUpdate {
            get {
                return ResourceManager.GetString("OneTime_Hint_NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneTime привязка к TextBox выше:.
        /// </summary>
        internal static string OneTime_Label_OneTimeBinding {
            get {
                return ResourceManager.GetString("OneTime_Label_OneTimeBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneTime привязка к тому же свойству:.
        /// </summary>
        internal static string OneTime_Label_OneTimeToVM {
            get {
                return ResourceManager.GetString("OneTime_Label_OneTimeToVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходное значение:.
        /// </summary>
        internal static string OneTime_Label_OriginalValue {
            get {
                return ResourceManager.GetString("OneTime_Label_OriginalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение из ViewModel:.
        /// </summary>
        internal static string OneTime_Label_ValueFromVM {
            get {
                return ResourceManager.GetString("OneTime_Label_ValueFromVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одноразовая привязка.
        /// </summary>
        internal static string OneTime_Title {
            get {
                return ResourceManager.GetString("OneTime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальное значение.
        /// </summary>
        internal static string SourceTextBox_DefaultText {
            get {
                return ResourceManager.GetString("SourceTextBox_DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одноразовая привязка.
        /// </summary>
        internal static string Tab_OneTimeBinding {
            get {
                return ResourceManager.GetString("Tab_OneTimeBinding", resourceCulture);
            }
        }
    }
}
